### ISSUE TITLE
Theme issue for Chrome Extension

### ISSUE THREAD

**Issue by lancescole** [aurelia/tools#53]
When using the Dark Theme for Chrome Developer Tools, the Aurelia Inspector extension becomes difficult to read.

**Comment by eriklieben** [comment]
Screenshot of issue:
![image](https://cloud.githubusercontent.com/assets/1912596/22757409/e430d396-ee4a-11e6-9e8a-d9af9c467034.png)

There is a related issue about this here: https://github.com/aurelia/inspector/issues/1

We can fix this by reading the following property:
```
this.isDark = (<any>chrome.devtools.panels).themeName === 'dark';
```
(I think this is new functionality in the latest Chome versions, because it isn't in the typescript definition yet.)

Not sure what would be a good option to set this, can be set as global ```.dark``` class on an upper html element and then  adjust the css like :
```
property-view .property-name {
  font-size: 12px;
  color: purple;
  font-family: monospace;
  margin-left: 1px;
}

.dark property-view .property-name {
  color: #34C7BB;
}
```
Or load a different css based upon the light or dark theme?

Tried the above property and adjusted some classes, seems like it works:
![image](https://cloud.githubusercontent.com/assets/1912596/22757282/7fcac7c2-ee4a-11e6-88c3-5045b71ba1d0.png)

**Comment by EisenbergEffect** [comment]
All the code, is in the inspector repo. @eriklieben If you want to submit a PR to address this, we can get it released.

**Comment by lancescole** [comment]
Thanks, that looks great.
